# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/working-with-dependabot/dependabot-options-reference

version: 2

multi-ecosystem-groups:
  minor-and-patch:
    schedule:
      interval: "quarterly"

updates:
  - package-ecosystem: "npm"
    directory: "/script/js"
    patterns: ["*"]
    multi-ecosystem-group: "minor-and-patch"
    groups:
      npm:
        update-types:
          - "minor"
          - "patch"
