# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/working-with-dependabot/dependabot-options-reference

version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/script/js"
    schedule:
      interval: "quarterly"
    cooldown:
      default-days: 5
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
    groups:
      npm:
        update-types:
          - "minor"
          - "patch"
