# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/working-with-dependabot/dependabot-options-reference

version: 2

multi-ecosystem-groups:
  minor-and-patch:
    schedule:
      interval: "quarterly"

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    patterns: ["*"]
    update-types: ["minor", "patch"]
    multi-ecosystem-group: "minor-and-patch"
  - package-ecosystem: "npm"
    directory: "/script/js"
    patterns: ["*"]
    update-types: ["minor", "patch"]
    multi-ecosystem-group: "minor-and-patch"
