tap "cloudflare/cloudflare"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-eid"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "vitorgalvao/tiny-scripts"
brew "archey"
brew "bash-completion"
brew "brew-cask-completion"
brew "cowsay"
brew "dnsperf"
brew "mas"
brew "node"
brew "nvm"
brew "pwgen"
brew "speedtest-cli"
brew "syncthing"
brew "terminal-notifier"
brew "thefuck"
brew "tldr"
brew "wget"
brew "yarn"
brew "youtube-dl"
brew "cloudflare/cloudflare/cloudflared"
brew "vitorgalvao/tiny-scripts/cask-repair"
cask "1password"
cask "1password-cli"
cask "adobe-creative-cloud"
cask "aerial"
cask "airtable"
cask "alfred"
cask "appcleaner"
cask "atom"
cask "discord"
cask "docker"
cask "dotnet-sdk"
cask "firefox"
cask "github"
cask "google-backup-and-sync"
cask "google-chrome"
cask "google-drive-file-stream"
cask "google-featured-photos"
cask "handbrake"
cask "hyper"
cask "java"
cask "kindle"
cask "kitematic"
cask "logitech-options"
cask "macdown"
cask "makemkv"
cask "marshallofsound-google-play-music-player"
cask "messenger"
cask "microsoft-office"
cask "now"
cask "plex-media-player"
cask "pongsaver"
cask "signal"
cask "skype"
cask "slack"
cask "sqlectron"
cask "table-tool"
cask "teamviewer"
cask "thingsmacsandboxhelper"
cask "tunnelbear"
cask "viscosity"
cask "vlc"
cask "wireshark"
mas "Annotate", id: 918207447
mas "Bear", id: 1091189122
mas "LG Screen Manager", id: 1142051783
mas "Magnet", id: 441258766
mas "Marked 2", id: 890031187
mas "Redacted", id: 984968384
mas "Speedtest", id: 1153157709
mas "Things3", id: 904280696
mas "Transmit", id: 403388562
