#!/usr/bin/env bash
#
# Run by github/github Codespaces after starting

# Install ZSH tools
apt install -y \
  zsh-autosuggestions \
  zsh-syntax-highlighting

# Install Starship
sh -c "$(curl -fsSL https://starship.rs/install.sh)" -- -y
