#!/usr/bin/env bash
#
# Run by Codespaces after starting

# Install Homebrew if not installed
if ! command -v brew >/dev/null; then
  # shellcheck source=/dev/null
  NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

  add_brew_config_to_file() {
    path="$1"
    line="eval \"\$($(brew --prefix)/bin/brew shellenv)\""
    if ! grep -qxF "$line" "$path"; then
      (echo; echo "$line") >> "$path"
    fi
  }

  # Add Homebrew to PATH
  test -d ~/.linuxbrew && eval "$(~/.linuxbrew/bin/brew shellenv)"
  test -d /home/linuxbrew/.linuxbrew && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
  test -r ~/.bashrc &&  add_brew_config_to_file ~/.bash_profile
  test -r ~/.bash_profile &&  add_brew_config_to_file ~/.bash_profile
  add_brew_config_to_file ~/.profile
fi

# Install fish if not installed
if ! command -v fish >/dev/null; then
  brew install fish && \

  # Set fish as the default shell
  echo /usr/local/bin/fish | sudo tee -a /etc/shells
  chsh -s /usr/local/bin/fish
fi

# Install font-fira-code-nerd-font (Starship dependency)
brew tap homebrew/cask-fonts
brew install font-fira-code-nerd-font

# Install Starship
brew install starship

# Disable Starship container configuration
echo "
[container]
disabled = true" >> ~/.config/starship.toml

# Use default commit signing configuration
git config --global --unset user.signingkey
git config --global --unset gpg.format
git config --global --unset gpg.ssh.program
git config --global --unset commit.gpgsign

# Install VSCode extensions
script/install-vscode-extensions
