#!/usr/bin/env bash
#
# Install VS Code extensions

echo ""
echo -e "\033[34mInstalling VS Code extensions...\033[0m"

if ! command -v code >/dev/null; then
  echo "Install VS Code first!" >&2
  exit 1
fi

# Get extensions to install from Brewfile
extensions="$(brew bundle list --vscode)"

# Get list of installed VS Code extensions
installed_extensions="$(code --list-extensions)"

# Iterate through each extension in the list
for extension in $extensions; do
  # Check if extension is already installed
  if [[ "$installed_extensions" == *"$extension"* ]]; then
    echo "Extension '$extension' is already installed."
  else
    # Install the extension
    code --install-extension "$extension"
  fi
done
