#!/bin/bash
#
# Install VS Code extensions

if ! command -v code >/dev/null; then
  echo "Install VS Code first!" >&2
  exit 1
fi

# Set vscode-extensions path
extensions="${BASH_SOURCE%/*}/../vscode-extensions"

# Get list of installed VS Code extensions
installed_extensions="$(code --list-extensions)"

# Iterate through each line of vscode-extensions
while IFS= read -r extension; do
  # Check if extension is already installed
  if [[ "$installed_extensions" == *"$extension"* ]]; then
    echo "Extension '$extension' is already installed."
  else
    # Install the extension
    #code --install-extension "$extension"
    echo "Extension '$extension' is not installed."
  fi
done <"$extensions"
