#!/usr/bin/env bash
#
# Run by Strap after installing Brewfile dependencies

cd "$(dirname "$0")"/.. || exit

# Only run on macOS
[[ "$OSTYPE" == darwin* ]] && {
  script/macos
  script/terminal
}

script/symlinks
script/install-vscode-extensions

# use zsh as the default shell
if [ "$SHELL" != "/bin/zsh" ]; then
  chsh -s /bin/zsh
fi
