#!/bin/sh
# Run by Strap after installing Brewfile dependencies

cd $(dirname $0)/..

script/macos
script/terminal
script/install-vscode-extensions

if [ "$SHELL" != "/bin/zsh" ]
then
  chsh -s /bin/zsh
fi
