#!/bin/sh
# Run by Strap after installing Brewfile dependencies

cd "$(dirname "$0")"/.. || exit

script/macos
script/symlinks
script/terminal
script/install-vscode-extensions

# use zsh as the default shell
if [ "$SHELL" != "/bin/zsh" ]
then
  chsh -s /bin/zsh
fi
