#!/bin/sh
# Create symbolic links

GITHUB_USERNAME=$(git config github.user)

ln -s Documents/github.com github.com && /
ln -s github.com/"$GITHUB_USERNAME"/exercism Exercism
ln -s ~/.dotfiles github.com/"$GITHUB_USERNAME"/dotfiles
