#!/bin/sh
# Create symbolic links

GITHUB_USERNAME=$(git config github.user)

ln -s Documents/GitHub GitHub
ln -s GitHub/$GITHUB_USERNAME/exercism Exercism
ln -s ~/.dotfiles GitHub/$GITHUB_USERNAME/dotfiles
