#!/bin/sh

# Clone the Prezto repository
git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"

# Copy the Prezto Zsh configuration files
setopt EXTENDED_GLOB
for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
  ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
done

# Setup Terminal profile
TERM_PROFILE=citrusui;
CURRENT_PROFILE="$(defaults read com.apple.terminal 'Default Window Settings')"; # check for current profile
if [ "${CURRENT_PROFILE}" != "${TERM_PROFILE}" ]; then
  open "${HOME}/.${TERM_PROFILE}.terminal"; # open new windows with citrusui profile
  sleep 1;
  # Set as default profile
  defaults write com.apple.terminal "Default Window Settings" -string "${TERM_PROFILE}";
  defaults write com.apple.terminal "Startup Window Settings" -string "${TERM_PROFILE}";
fi;
