#!/bin/sh
# Setup Terminal profile

TERM_PROFILE=xyz;
CURRENT_PROFILE="$(defaults read com.apple.terminal 'Default Window Settings')";

if [ "${CURRENT_PROFILE}" != "${TERM_PROFILE}" ]; then
  # open new windows with TERM_PROFILE
  open "${HOME}/.${TERM_PROFILE}.terminal";
  sleep 1;
  # Set as default profile
  defaults write com.apple.terminal "Default Window Settings" -string "${TERM_PROFILE}";
  defaults write com.apple.terminal "Startup Window Settings" -string "${TERM_PROFILE}";
fi;
