#!/usr/bin/env bash

# Change the working directory to the script/js directory
cd "$(dirname "$0")"/js || exit

# Run the script and redirect output to Brewfile in the parent directory
npx zx generate-brewfile.mjs > ../../Brewfile
